### PR TITLE
[NEED TEST]  Refactor calfw's code

### PR DESCRIPTION
**Pull request by tumashu**
The goal of  this pull request:
1.  Use "calfw-" instead of "cfw:" prefix
2.  Remove all compile warn and error
3.  Switch to cl-lib from cl
4.  Lexical-binding: t
5.  Support split melpa packages: calfw to  calfw, calfw-org, calfw-ical, calfw-cal, calfw-howm, please see: https://github.com/melpa/melpa/pull/4850

### CODE REVIEW

**Comment by kiwanami** [comment]
Hi @tumashu 
I'm sorry for my late response.
Your work seems to be great.

I'll wait for finishing your work.
I think it may be much time for me to check the changes...

**Comment by tumashu** [comment]
ok

**Comment by tumashu** [comment]
At the moment, all the work I can do have finished,  I tested the basic function and  cfw-org.el, seem to work as before,  cfw-cal, cfw-ical ,cfw-howm are not tested. 

```
(url-http-symbol-value-in-buffer
              'url-http-end-of-headers buf)
```
in cfw-ical.el is can not found, this should deal with by yourself, for I don know how to deal with it.

Please check and comment.

**Comment by tumashu** [comment]
Resolve the conflict :-)

**Comment by tumashu** [comment]
In my opinion, "calfw-" is a very very good prefix than  "cfw:" or "cfw-", so I think if we want to refactor the code to a new start, using "calfw-" is a good idea.

**Comment by tumashu** [comment]
Is this PR status?

**Comment by tumashu** [comment]
seem to no repons....

**Pull request closed without merging**
